/**
 * 工具元数据：导航、命令面板、SEO 标题都从这里取。
 * keywords 用于命令面板搜索（中英文、常见别名）。
 */
export const tools = [
  {
    id: 'qrcode',
    name: '二维码',
    icon: '📱',
    color: '#ff6b6b',
    description: '生成可下载的二维码，或上传图片识别二维码内容',
    keywords: ['二维码', 'qrcode', 'qr', '生成', '扫码', '识别', 'scan'],
  },
  {
    id: 'json',
    name: 'JSON',
    icon: '📄',
    color: '#4ecdc4',
    description: 'JSON 格式化、压缩、校验与树形浏览',
    keywords: ['json', '格式化', 'format', '美化', '压缩', 'minify', '树', 'tree'],
  },
  {
    id: 'encrypt',
    name: '文本加密',
    icon: '🔐',
    color: '#9c27b0',
    description: 'MD5 / SHA 哈希与 AES 加密解密',
    keywords: ['加密', '解密', '哈希', 'hash', 'md5', 'sha', 'sha256', 'aes', 'encrypt'],
  },
  {
    id: 'encoding',
    name: '编码/解码',
    icon: '🔤',
    color: '#4ecdc4',
    description: 'Base64 与 URL 编码解码，支持中文与 emoji',
    keywords: ['编码', '解码', 'base64', 'url', 'encode', 'decode', 'urlencode'],
  },
  {
    id: 'regex',
    name: '正则表达式',
    icon: '🔍',
    color: '#ffa502',
    description: '测试、高亮与替换正则匹配结果',
    keywords: ['正则', 'regex', 'regexp', '表达式', '匹配', '替换', 'replace'],
  },
  {
    id: 'markdown',
    name: 'Markdown',
    icon: '📝',
    color: '#2196f3',
    description: 'Markdown 实时预览，导出 HTML 或 .md 文件',
    keywords: ['markdown', 'md', '预览', 'preview', 'html', '导出'],
  },
  {
    id: 'time',
    name: '时间工具',
    icon: '⏰',
    color: '#2196f3',
    description: '时间戳与日期互转、时间单位换算',
    keywords: ['时间', '时间戳', '日期', 'time', 'timestamp', 'date', 'unix', '毫秒'],
  },
  {
    id: 'convert',
    name: '单位转换',
    icon: '🔄',
    color: '#ff6b6b',
    description: '长度、温度、重量、体积与进制转换',
    keywords: ['转换', '单位', '长度', '温度', '重量', '体积', '进制', 'convert', 'unit', 'hex', 'binary'],
  },
  {
    id: 'color',
    name: '颜色工具',
    icon: '🎨',
    color: '#9c27b0',
    description: 'HEX / RGB / HSL 互转，配色与色板',
    keywords: ['颜色', '色彩', 'color', 'hex', 'rgb', 'hsl', '配色', '色板', 'palette'],
  },
  {
    id: 'validator',
    name: '数据验证',
    icon: '✔️',
    color: '#42b883',
    description: '邮箱、手机号、URL、IP、身份证格式校验',
    keywords: ['验证', '校验', '邮箱', '手机', '身份证', 'ip', 'email', 'validator', 'validate'],
  },
  {
    id: 'network',
    name: '网络工具',
    icon: '🌐',
    color: '#2196f3',
    description: '网址分析、DNS 查询与本机 IP 信息',
    keywords: ['网络', 'dns', 'ip', 'network', '域名', '网址', 'url'],
  },
  {
    id: 'urltools',
    name: 'URL 工具',
    icon: '🔗',
    color: '#2196f3',
    description: 'URL 解析、编码与 Query ↔ JSON 互转',
    keywords: ['url', 'query', 'querystring', 'encode', 'decode', '解析', '参数', '链接'],
  },
  {
    id: 'csvjson',
    name: 'CSV ↔ JSON',
    icon: '🧾',
    color: '#00bcd4',
    description: 'CSV / TSV 与 JSON 数组互转',
    keywords: ['csv', 'tsv', 'json', '转换', '表格', 'excel', 'table'],
  },
  {
    id: 'curlfetch',
    name: 'cURL 转 Fetch',
    icon: '🌀',
    color: '#2196f3',
    description: '把 curl 命令转换为浏览器 fetch 代码',
    keywords: ['curl', 'fetch', '转换', '请求', 'http', 'api'],
  },
  {
    id: 'chmod',
    name: '权限换算',
    icon: '🛡️',
    color: '#607d8b',
    description: 'Linux chmod 八进制与 rwx 表示互转',
    keywords: ['chmod', '权限', 'rwx', '755', '644', 'linux', 'permission'],
  },
  {
    id: 'notes',
    name: '笔记 & TODO',
    icon: '📝',
    color: '#9c27b0',
    description: '本地保存的笔记与待办清单，支持标签与导出',
    keywords: ['笔记', '待办', '任务', 'notes', 'todo', '备忘'],
  },
  {
    id: 'textadvanced',
    name: '文本处理',
    icon: '✨',
    color: '#ff6b6b',
    description: 'UUID、密码生成，大小写转换、去重与字数统计',
    keywords: ['文本', 'uuid', '密码', '去重', '大小写', 'camel', 'snake', '统计', 'password'],
  },
  {
    id: 'calculator',
    name: '计算器',
    icon: '🧮',
    color: '#2196f3',
    description: '带历史记录的基础计算器',
    keywords: ['计算', '计算器', 'calculator', '数学', 'math'],
  },
  {
    id: 'codeformatter',
    name: '代码工具',
    icon: '💻',
    color: '#9c27b0',
    description: 'JSON / SQL / HTML / XML 格式化与压缩',
    keywords: ['代码', '格式化', 'sql', 'html', 'xml', 'format', 'beautify', 'minify'],
  },
  {
    id: 'fileconverter',
    name: '文件转换',
    icon: '🔄',
    color: '#4ecdc4',
    description: '图片与 Base64 互转、文件哈希计算',
    keywords: ['文件', '图片', 'base64', '哈希', 'hash', 'md5', 'file'],
  },
  {
    id: 'jwt',
    name: 'JWT 解码',
    icon: '🔑',
    color: '#ff6b6b',
    description: '解析 JWT 的 Header / Payload 并检查有效期',
    keywords: ['jwt', 'token', '解码', '令牌', 'json web token', 'decode'],
  },
  {
    id: 'cron',
    name: 'Cron解析',
    icon: '⏱️',
    color: '#e91e63',
    description: '解释 Cron 表达式并预测接下来的执行时间',
    keywords: ['cron', '定时', '计划任务', '表达式', 'crontab', 'schedule'],
  },
  {
    id: 'diff',
    name: '文本对比',
    icon: '📄',
    color: '#00bcd4',
    description: '逐行对比两段文本，支持并排视图与统一 diff 导出',
    keywords: ['对比', '差异', 'diff', '比较', 'compare'],
  },
  {
    id: 'datagen',
    name: '数据生成',
    icon: '🎲',
    color: '#ff9800',
    description: '占位文本、随机姓名、邮箱、手机号与 JSON 模拟数据',
    keywords: ['生成', '模拟', '随机', '数据', 'mock', 'fake', 'lorem'],
  },
  {
    id: 'cssunit',
    name: 'CSS单位',
    icon: '📐',
    color: '#607d8b',
    description: 'px / rem / em / vw / vh 互转与速查表',
    keywords: ['css', '单位', 'px', 'rem', 'em', 'vw', 'vh', '转换'],
  },
  {
    id: 'imgcompress',
    name: '图片压缩',
    icon: '🖼️',
    color: '#8bc34a',
    description: '浏览器内压缩、缩放并转换图片格式',
    keywords: ['图片', '压缩', '缩小', 'image', 'compress', 'webp', 'jpg', 'png'],
  },
  {
    id: 'htmlentity',
    name: 'HTML实体',
    icon: '🔣',
    color: '#795548',
    description: 'HTML 实体与普通字符互转',
    keywords: ['html', '实体', '转义', 'entity', 'escape', '&amp;'],
  },
  {
    id: 'configconvert',
    name: '配置转换',
    icon: '⚙️',
    color: '#ff9800',
    description: 'JSON / YAML / TOML 配置文件互转',
    keywords: ['配置', 'json', 'yaml', 'yml', 'toml', '转换', 'config'],
  },
  {
    id: 'lottery',
    name: '抽奖工具',
    icon: '🎰',
    color: '#e91e63',
    description: '幸运转盘、权重抽奖、模板与抽奖记录',
    keywords: ['抽奖', '随机', '轮盘', '抽签', '转盘', 'lottery', 'random'],
  },
  {
    id: 'metalprice',
    name: '金属行情',
    icon: '📉',
    color: '#d4a017',
    description: '黄金、白银、铜实时价格与走势图',
    keywords: ['金价', '黄金', '白银', '铜', '行情', '价格', '金属', 'gold', 'silver', 'copper', 'price'],
  },
  {
    id: 'storage',
    name: '历史/收藏',
    icon: '📚',
    color: '#4ecdc4',
    description: '浏览、搜索并管理历史记录与收藏',
    keywords: ['历史', '收藏', '记录', 'history', 'favorite', 'bookmark'],
  },
  {
    id: 'settings',
    name: '设置',
    icon: '⚙️',
    color: '#4ecdc4',
    description: '主题、数据备份恢复与存储管理',
    keywords: ['设置', '主题', '配置', '导入', '导出', '备份', 'settings', 'theme', 'backup'],
  },
]

export const categoryGroups = [
  { category: '基础工具', ids: ['qrcode', 'json'] },
  { category: '编码转换', ids: ['encrypt', 'encoding', 'regex', 'jwt', 'htmlentity', 'configconvert'] },
  { category: '内容处理', ids: ['markdown', 'diff'] },
  { category: '数据转换', ids: ['time', 'convert', 'color', 'cssunit'] },
  { category: '验证工具', ids: ['validator', 'network', 'cron', 'urltools'] },
  { category: '开发辅助', ids: ['csvjson', 'curlfetch', 'chmod'] },
  {
    category: '高级工具',
    ids: ['textadvanced', 'calculator', 'codeformatter', 'fileconverter', 'datagen', 'imgcompress', 'lottery', 'metalprice'],
  },
  { category: '数据管理', ids: ['notes', 'storage', 'settings'] },
]

export const toolCategoryMap = new Map(
  categoryGroups.flatMap((group) => group.ids.map((id) => [id, group.category])),
)
