export const tools = [
  { id: 'qrcode', name: '二维码', icon: '📱', color: '#ff6b6b' },
  { id: 'json', name: 'JSON', icon: '📄', color: '#4ecdc4' },
  { id: 'encrypt', name: '文本加密', icon: '🔐', color: '#9c27b0' },
  { id: 'encoding', name: '编码/解码', icon: '🔤', color: '#4ecdc4' },
  { id: 'regex', name: '正则表达式', icon: '🔍', color: '#ffa502' },
  { id: 'markdown', name: 'Markdown', icon: '📝', color: '#2196f3' },
  { id: 'time', name: '时间工具', icon: '⏰', color: '#2196f3' },
  { id: 'convert', name: '单位转换', icon: '🔄', color: '#ff6b6b' },
  { id: 'color', name: '颜色工具', icon: '🎨', color: '#9c27b0' },
  { id: 'validator', name: '数据验证', icon: '✔️', color: '#42b883' },
  { id: 'network', name: '网络工具', icon: '🌐', color: '#2196f3' },
  { id: 'urltools', name: 'URL 工具', icon: '🔗', color: '#2196f3' },
  { id: 'csvjson', name: 'CSV ↔ JSON', icon: '🧾', color: '#00bcd4' },
  { id: 'curlfetch', name: 'cURL 转 Fetch', icon: '🌀', color: '#2196f3' },
  { id: 'chmod', name: '权限换算', icon: '🛡️', color: '#607d8b' },
  { id: 'notes', name: '笔记 & TODO', icon: '📝', color: '#9c27b0' },
  { id: 'textadvanced', name: '文本处理', icon: '✨', color: '#ff6b6b' },
  { id: 'calculator', name: '计算器', icon: '🧮', color: '#2196f3' },
  { id: 'codeformatter', name: '代码工具', icon: '💻', color: '#9c27b0' },
  { id: 'fileconverter', name: '文件转换', icon: '🔄', color: '#4ecdc4' },
  { id: 'jwt', name: 'JWT 解码', icon: '🔑', color: '#ff6b6b' },
  { id: 'cron', name: 'Cron解析', icon: '⏱️', color: '#e91e63' },
  { id: 'diff', name: '文本对比', icon: '📄', color: '#00bcd4' },
  { id: 'datagen', name: '数据生成', icon: '🎲', color: '#ff9800' },
  { id: 'cssunit', name: 'CSS单位', icon: '📐', color: '#607d8b' },
  { id: 'imgcompress', name: '图片压缩', icon: '🖼️', color: '#8bc34a' },
  { id: 'htmlentity', name: 'HTML实体', icon: '🔣', color: '#795548' },
  { id: 'configconvert', name: '配置转换', icon: '⚙️', color: '#ff9800' },
  { id: 'lottery', name: '抽奖工具', icon: '🎰', color: '#e91e63' },
  { id: 'metalprice', name: '金属行情', icon: '📉', color: '#d4a017' },
  { id: 'storage', name: '历史/收藏', icon: '📚', color: '#4ecdc4' },
  { id: 'settings', name: '设置', icon: '⚙️', color: '#4ecdc4' },
]

export const categoryGroups = [
  { category: '基础工具', ids: ['qrcode', 'json'] },
  { category: '编码转换', ids: ['encrypt', 'encoding', 'regex', 'jwt', 'htmlentity', 'configconvert'] },
  { category: '内容处理', ids: ['markdown', 'diff'] },
  { category: '数据转换', ids: ['time', 'convert', 'color', 'cssunit'] },
  { category: '验证工具', ids: ['validator', 'network', 'cron', 'urltools'] },
  { category: '开发辅助', ids: ['csvjson', 'curlfetch', 'chmod'] },
  {
    category: '高级工具',
    ids: ['textadvanced', 'calculator', 'codeformatter', 'fileconverter', 'datagen', 'imgcompress', 'lottery', 'metalprice'],
  },
  { category: '数据管理', ids: ['notes', 'storage', 'settings'] },
]
